services:
  grafana:
    image: grafana/grafana-oss:12.1.0
    restart: unless-stopped
    user: "{{ docker_compose_uid }}:{{ docker_compose_gid }}"
    volumes:
      - "{{ grafana_docker_volumes.data }}:/var/lib/grafana"
      - "{{ grafana_config_folders.provisioning }}:/etc/grafana/provisioning:ro"
    networks:
      - {{ monitoring.network_name }}
      - {{ traefik.network_name }}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`{{ homelab_services.grafana.domain }}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=ovh"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network={{ traefik.network_name }}"

networks:
  {{ monitoring.network_name }}:
    external: true
  {{ traefik.network_name }}:
    external: true
